### ISSUE TITLE
网页信息显示错误

### ISSUE THREAD

**Issue by BredyAK** [NyaaCat/NyaaStats#22]
如图，网站显示出现以下错误：

- 世界历时变成三个点（“...”），而不是具体时长；
- 左上角两个标题消失；

Minecraft服务器版本：1.16.1

哪里出现了错误？如何修正？谢谢解答。

**Comment by SilentDepth** [comment]
目前尚不支持 1.16.x 的数据（你在执行第一步 `npm run start` 的时候应该会看到报错）

**Comment by BredyAK** [comment]
> 目前尚不支持 1.16.x 的数据（你在执行第一步 `npm run start` 的时候应该会看到报错）

好的，确实在很多地方遇到很奇怪的报错。期待版本跟进。是否方便留下联系方式？很不错的项目，希望认识一下。

**Comment by BredyAK** [comment]
> 目前尚不支持 1.16.x 的数据（你在执行第一步 `npm run start` 的时候应该会看到报错）

你好，请问现在支持了吗？

**Comment by SilentDepth** [comment]
1.16.x 支持尚未正式上线。如果你愿意尝试开发版本，可以使用 [1.16 分支](https://github.com/NyaaCat/NyaaStats/tree/1.16)试试

**Comment by BredyAK** [comment]
> 1.16.x 支持尚未正式上线。如果你愿意尝试开发版本，可以使用 [1.16 分支](https://github.com/NyaaCat/NyaaStats/tree/1.16)试试

已测试，网站为白屏状态，一直显示“LOADING”。见下图：

![白屏](https://i.ibb.co/xShp4m9/QQ-20200724135934.png "白屏")

**Comment by SilentDepth** [comment]
发一下浏览器控制台的报错信息。如果你保留了主程序的运行日志并且其中包含错误，最好也发一下。

**Comment by BredyAK** [comment]
控制台报错（黄色叹号warnings，并非errors）：
```
DevTools failed to load SourceMap: Could not parse content for https://i.kamicraft.com/js/chunk-vendors.6fc3f5e0.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://i.kamicraft.com/js/app.4145500a.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://i.kamicraft.com/js/chunk-f424b38a.73615532.js.map: Unexpected token < in JSON at position 0
DevTools failed to load SourceMap: Could not parse content for https://i.kamicraft.com/js/chunk-eb5e686e.f3ae7a27.js.map: Unexpected token < in JSON at position 0
```
运行日志没有找到在哪里看，抱歉。

**Comment by SilentDepth** [comment]
看起来 web 端没有出现关键问题。从你的截图来看，`/data/players.json` 有异常。检查一下你的 HTTP 部署，看看这个文件是否存在。如果该文件不存在，或者内容异常，以下列命令重新执行主程序：

```sh
npm run start > grabber.log
```

这样会把主程序的运行日志输出到 `grabber.log` 文件中，把这个文件的内容发一下。文件内容可能很多，你可以上传到 Gist。

**Comment by BredyAK** [comment]
我在NyaaStats主目录执行了上述命令，但报错了。在`npm start`更新玩家数据时会出现同样的错误。

```
[root@HytaleBBS-Website NyaaStats]# npm run start > grabber.log

(node:2201) UnhandledPromiseRejectionWarning: Error: Error: Tag type 12 is not supported by this module yet.
    at /website/repositories/NyaaStats_old/index.js:96:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2201) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

另外，我重新clone了项目然后安装。我觉得有必要把整个过程日志给你看下。

1. Clone后`npm install`：https://pastebin.com/Nee3MYVg
2. 第一次执行`npm start`后全绿无报错，但打开`players.json`发现是空的。（只有`[]`）
3. 从第2次执行`npm start`开始都会在最后报错：https://pastebin.com/ssESjN5j

**Comment by SilentDepth** [comment]
fcf8fede 修复了这个错误，你再试一下

**Comment by BredyAK** [comment]
一样的，网页卡在LOADING，`players.json`还是空的。

**Comment by SilentDepth** [comment]
主程序的运行日志呢？

**Comment by BredyAK** [comment]
> 主程序的运行日志呢？

这是跑了一遍`npm run start > grabber.log`的：https://pastebin.com/VQNBd0ha

`players.json`依然是空的，而且日志里貌似没什么错误，太奇怪了。

**Comment by SilentDepth** [comment]
[v2.2.0](https://github.com/NyaaCat/NyaaStats/tree/v2.2.0) 已发布，试试看有没有修复你的问题。如果问题依然存在，请另开 Issue 汇报并附上程序日志和浏览器控制台错误信息。
